#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# Autostart
sxhkd &

if [ -x ~/bin/bspwm_monitor ];then
    ~/bin/bspwm_monitor
fi


# panel
~/.config/polybar/launch.sh &

# Set some bsp specific stuff
bspc monitor eDP1 -d  1 2 3 4 5
bspc monitor HDMI2 -d 6 7 8 9 0

### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#### BSPWM Coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#### App Rules
bspc rule -a Zathura state==tiled

